import React, { useState } from 'react';
import { 
  FileText, 
  X, 
  Copy, 
  Check, 
  Download, 
  Printer, 
  TrendingUp, 
  ShieldAlert, 
  Lightbulb,
  Building2,
  DollarSign
} from 'lucide-react';
import { 
  computeHealthScore, 
  detectRisks, 
  formatCurrency, 
  calculateLinearRegression, 
  generateForecast 
} from '../data/mockData';

export default function ExecutiveReportModal({ 
  isOpen, 
  onClose, 
  profile, 
  metrics, 
  products, 
  channels, 
  segments, 
  recommendations 
}) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const healthScore = computeHealthScore(metrics, channels, products);
  const risks = detectRisks(metrics, channels, products);
  const regression = calculateLinearRegression(metrics);
  const forecast = generateForecast(metrics, 3);

  const latest = metrics[metrics.length - 1] || {};
  const revenue = latest.revenue || 0;
  const totalCost = (latest.cogs || 0) + (latest.operatingExpenses || 0) + (latest.marketingSpend || 0);
  const netProfit = revenue - totalCost;
  const marginPercent = revenue > 0 ? (netProfit / revenue) * 100 : 0;
  const runwayMonths = totalCost > 0 ? (latest.cashBuffer || 50000) / totalCost : 12;

  const reportText = `=====================================================
EXECUTIVE BUSINESS CONSULTING REPORT & ADVISORY
Generated by BizConsult AI Decision Engine
Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
=====================================================

1. BUSINESS PROFILE
- Company: ${profile?.companyName || 'Business'}
- Industry: ${profile?.industry || 'General'}
- Stage: ${profile?.stage || 'Growth'}
- Target Audience: ${profile?.targetAudience || 'Target market'}
- Strategic Goal: ${profile?.primaryGoal || 'Profit Optimization'}

2. FINANCIAL VITAL SIGNS (LATEST MONTH)
- Monthly Revenue: ${formatCurrency(revenue)}
- Net Profit: ${formatCurrency(netProfit)} (Net Margin: ${marginPercent.toFixed(1)}%)
- Operating Cost: ${formatCurrency(totalCost)}
- Cash Runway: ${runwayMonths.toFixed(1)} Months (Reserves: ${formatCurrency(latest.cashBuffer || 0)})
- Composite Health Score: ${healthScore.overall}/100 [Grade: ${healthScore.grade}]
- Evaluation: ${healthScore.summary}

3. PREDICTIVE FORECAST (NEXT 3 MONTHS)
- Trend: ${regression.trend} (${(regression.avgGrowthRate * 100).toFixed(1)}% Avg MoM)
${forecast.map(f => `  * ${f.month}: ${formatCurrency(f.projectedRevenue)} (Range: ${formatCurrency(f.lowerBound)} - ${formatCurrency(f.upperBound)})`).join('\n')}

4. CRITICAL RISKS & VULNERABILITIES
${risks.map(r => `  * [${r.severity}] ${r.title} - ${r.description}\n    Action: ${r.hint}`).join('\n')}

5. TOP STRATEGIC RECOMMENDATIONS
${recommendations.slice(0, 4).map((rec, i) => `  ${i + 1}. [${rec.priority} Priority] ${rec.title}\n     Impact: ${rec.expectedImpact}\n     Summary: ${rec.summary}`).join('\n')}

=====================================================
CONFIDENTIAL & PROPRIETARY — PREPARED FOR EXECUTIVE LEADERSHIP
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${profile?.companyName?.replace(/\s+/g, '_') || 'BizConsult'}_Executive_Report.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-3xl glass-card rounded-2xl border border-slate-800 p-6 sm:p-8 shadow-2xl flex flex-col max-h-[90vh]">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-800 shrink-0">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-tr from-cyan-500 to-blue-600 text-slate-950 font-bold shadow-md shadow-cyan-500/20">
              <FileText className="h-5 w-5 text-white" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-lg font-bold text-white">Executive Advisory Briefing</h3>
                <span className="rounded-full bg-cyan-950 px-2 py-0.5 text-[10px] font-bold text-cyan-400 border border-cyan-800">
                  CONFIDENTIAL
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Prepared for {profile?.companyName} • {new Date().toLocaleDateString()}
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Scrollable Report Content */}
        <div className="mt-4 flex-1 overflow-y-auto space-y-6 pr-2">
          
          {/* Executive Summary Cards */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="rounded-xl bg-slate-900/90 border border-slate-800 p-3.5">
              <p className="text-[11px] font-semibold text-slate-400">Monthly Revenue</p>
              <p className="text-lg font-bold text-white mt-1">{formatCurrency(revenue)}</p>
              <p className="text-[10px] text-cyan-400">Latest Period</p>
            </div>

            <div className="rounded-xl bg-slate-900/90 border border-slate-800 p-3.5">
              <p className="text-[11px] font-semibold text-slate-400">Net Margin</p>
              <p className={`text-lg font-bold mt-1 ${marginPercent >= 15 ? 'text-emerald-400' : 'text-amber-400'}`}>
                {marginPercent.toFixed(1)}%
              </p>
              <p className="text-[10px] text-slate-400">{formatCurrency(netProfit)} net profit</p>
            </div>

            <div className="rounded-xl bg-slate-900/90 border border-slate-800 p-3.5">
              <p className="text-[11px] font-semibold text-slate-400">Cash Runway</p>
              <p className={`text-lg font-bold mt-1 ${runwayMonths >= 6 ? 'text-emerald-400' : 'text-rose-400'}`}>
                {runwayMonths.toFixed(1)} Mo
              </p>
              <p className="text-[10px] text-slate-400">{formatCurrency(latest.cashBuffer || 0)} reserves</p>
            </div>

            <div className="rounded-xl bg-slate-900/90 border border-slate-800 p-3.5">
              <p className="text-[11px] font-semibold text-slate-400">Health Score</p>
              <p className="text-lg font-bold text-cyan-400 mt-1">{healthScore.overall}/100</p>
              <p className="text-[10px] text-slate-400">Rating: {healthScore.grade}</p>
            </div>
          </div>

          {/* Forecast Box */}
          <div className="rounded-xl bg-slate-900/60 border border-slate-800 p-4">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-2 flex items-center gap-1.5">
              <TrendingUp className="h-4 w-4 text-cyan-400" />
              <span>3-Month Predictive Forecast</span>
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {forecast.map((f, i) => (
                <div key={i} className="rounded-lg bg-slate-950 p-3 border border-slate-800">
                  <p className="text-xs font-semibold text-slate-300">{f.month}</p>
                  <p className="text-base font-bold text-cyan-400 mt-0.5">{formatCurrency(f.projectedRevenue)}</p>
                  <p className="text-[10px] text-slate-500">Range: {formatCurrency(f.lowerBound)} – {formatCurrency(f.upperBound)}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Action Recommendations */}
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-2 flex items-center gap-1.5">
              <Lightbulb className="h-4 w-4 text-amber-400" />
              <span>Key Strategic Interventions</span>
            </h4>
            <div className="space-y-2">
              {recommendations.slice(0, 4).map((rec, i) => (
                <div key={i} className="rounded-xl bg-slate-900/90 border border-slate-800 p-3.5 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                        rec.priority === 'High' ? 'bg-rose-500/20 text-rose-400' : 'bg-amber-500/20 text-amber-400'
                      }`}>
                        {rec.priority}
                      </span>
                      <p className="text-xs font-bold text-white">{rec.title}</p>
                    </div>
                    <p className="text-[11px] text-slate-400 mt-1">{rec.summary}</p>
                  </div>
                  <div className="text-right shrink-0">
                    <span className="text-xs font-bold text-emerald-400">{rec.expectedImpact}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Risk Factors */}
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-2 flex items-center gap-1.5">
              <ShieldAlert className="h-4 w-4 text-rose-400" />
              <span>Identified Vulnerabilities</span>
            </h4>
            <div className="space-y-2">
              {risks.map((r, i) => (
                <div key={i} className="rounded-xl bg-slate-900/50 border border-slate-800 p-3 flex items-start gap-3">
                  <div className={`mt-0.5 h-2 w-2 rounded-full shrink-0 ${
                    r.severity === 'CRITICAL' ? 'bg-rose-500' : r.severity === 'WARNING' ? 'bg-amber-500' : 'bg-emerald-500'
                  }`} />
                  <div>
                    <p className="text-xs font-semibold text-slate-200">{r.title}</p>
                    <p className="text-[11px] text-slate-400 mt-0.5">{r.description}</p>
                    <p className="text-[10px] text-cyan-400 mt-1">Recommended: {r.hint}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* Footer Actions */}
        <div className="mt-4 pt-4 border-t border-slate-800 flex flex-wrap items-center justify-between gap-3 shrink-0">
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 rounded-xl border border-slate-700 bg-slate-900 px-3.5 py-2 text-xs font-semibold text-slate-200 hover:bg-slate-800 transition-colors"
            >
              {copied ? <Check className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4 text-slate-400" />}
              <span>{copied ? 'Copied to Clipboard!' : 'Copy Summary'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 rounded-xl border border-slate-700 bg-slate-900 px-3.5 py-2 text-xs font-semibold text-slate-200 hover:bg-slate-800 transition-colors"
            >
              <Download className="h-4 w-4 text-slate-400" />
              <span>Export .txt</span>
            </button>

            <button
              onClick={handlePrint}
              className="hidden sm:flex items-center gap-1.5 rounded-xl border border-slate-700 bg-slate-900 px-3.5 py-2 text-xs font-semibold text-slate-200 hover:bg-slate-800 transition-colors"
            >
              <Printer className="h-4 w-4 text-slate-400" />
              <span>Print</span>
            </button>
          </div>

          <button
            onClick={onClose}
            className="rounded-xl bg-cyan-500 px-5 py-2 text-xs font-bold text-slate-950 hover:bg-cyan-400 transition-colors"
          >
            Done
          </button>
        </div>

      </div>
    </div>
  );
}
