package com.example.ui.dialogs

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Dialog
import com.example.data.local.*
import com.example.domain.analytics.*
import com.example.ui.theme.*

@Composable
fun ExecutiveReportDialog(
    profile: BusinessProfileEntity?,
    metrics: List<MonthlyMetricEntity>,
    channels: List<MarketingChannelEntity>,
    products: List<ProductPerformanceEntity>,
    recommendations: List<BusinessRecommendationEntity>,
    onDismiss: () -> Unit
) {
    val context = LocalContext.current
    val scrollState = rememberScrollState()

    val healthScore = remember(metrics, channels, products) {
        RiskScoringEngine.computeHealthScore(metrics, channels, products)
    }

    val forecast = remember(metrics) {
        PredictiveEngine.generateForecast(metrics, 3)
    }

    val reportText = remember(profile, metrics, healthScore, forecast, recommendations) {
        val latest = metrics.lastOrNull()
        val latestRev = latest?.revenue ?: 0.0
        val latestCost = (latest?.cogs ?: 0.0) + (latest?.operatingExpenses ?: 0.0) + (latest?.marketingSpend ?: 0.0)
        val profit = latestRev - latestCost
        val margin = if (latestRev > 0) (profit / latestRev) * 100 else 0.0

        buildString {
            appendLine("==================================================")
            appendLine("   BIZADVISOR AI — EXECUTIVE CONSULTING BRIEF   ")
            appendLine("==================================================")
            appendLine("Client: ${profile?.companyName ?: "Business"}")
            appendLine("Industry: ${profile?.industry ?: "General SMB"} | Goal: ${profile?.primaryGoal}")
            appendLine("Health Score: ${healthScore.overallScore}/100 (Rating: ${healthScore.ratingGrade})")
            appendLine("Date: September 2026")
            appendLine()
            appendLine("--- 1. FINANCIAL VITAL SIGNS ---")
            appendLine("• Monthly Revenue: ${latestRev.formatCurrency()}")
            appendLine("• Total Expenses: ${latestCost.formatCurrency()}")
            appendLine("• Net Operating Profit: ${profit.formatCurrency()} (${margin.format(1)}% margin)")
            appendLine("• Customer Churn Rate: ${((latest?.churnRate ?: 0.04) * 100).format(1)}%")
            appendLine("• Cash Reserves: ${(latest?.cashBuffer ?: 50000.0).formatCurrency()} (${if (latestCost > 0) ((latest?.cashBuffer ?: 50000.0) / latestCost).format(1) else "12"} mo runway)")
            appendLine()
            appendLine("--- 2. PREDICTIVE REVENUE FORECAST (Q4) ---")
            forecast.forEach { f ->
                appendLine("• ${f.monthName}: ${f.predictedRevenue.formatCurrency()} (Est. range: ${f.lowerBound.formatCurrency()} - ${f.upperBound.formatCurrency()})")
            }
            appendLine()
            appendLine("--- 3. HIGH-PRIORITY ACTION PLAN ---")
            recommendations.take(3).forEachIndexed { idx, r ->
                appendLine("${idx + 1}. [${r.priority.uppercase()}] ${r.title}")
                appendLine("   Impact: ${r.expectedImpact}")
                appendLine("   Rationale: ${r.summary}")
            }
            appendLine()
            appendLine("==================================================")
            appendLine("Generated by BizAdvisor AI Consultant Engine")
        }
    }

    Dialog(onDismissRequest = onDismiss) {
        Surface(
            shape = RoundedCornerShape(20.dp),
            color = Navy900,
            border = androidx.compose.foundation.BorderStroke(1.dp, Navy700),
            modifier = Modifier
                .fillMaxWidth()
                .fillMaxHeight(0.85f)
        ) {
            Column(modifier = Modifier.padding(20.dp)) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = "Executive Briefing Report",
                        style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold, color = White)
                    )

                    IconButton(onClick = onDismiss, modifier = Modifier.size(32.dp)) {
                        Icon(Icons.Default.Close, contentDescription = "Close", tint = Slate400)
                    }
                }

                Spacer(modifier = Modifier.height(12.dp))

                // Scrollable Brief Box
                Surface(
                    color = Navy800,
                    shape = RoundedCornerShape(12.dp),
                    modifier = Modifier
                        .weight(1f)
                        .fillMaxWidth()
                ) {
                    Column(
                        modifier = Modifier
                            .padding(14.dp)
                            .verticalScroll(scrollState)
                    ) {
                        Text(
                            text = reportText,
                            style = MaterialTheme.typography.bodySmall.copy(
                                color = Slate200,
                                fontFamily = androidx.compose.ui.text.font.FontFamily.Monospace,
                                fontSize = 11.sp,
                                lineHeight = 18.sp
                            )
                        )
                    }
                }

                Spacer(modifier = Modifier.height(16.dp))

                // Action Buttons
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    OutlinedButton(
                        onClick = {
                            val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                            val clip = ClipData.newPlainText("Executive Brief", reportText)
                            clipboard.setPrimaryClip(clip)
                            Toast.makeText(context, "Copied report to clipboard", Toast.LENGTH_SHORT).show()
                        },
                        modifier = Modifier.weight(1f).testTag("copy_report_button"),
                        shape = RoundedCornerShape(10.dp),
                        border = androidx.compose.foundation.BorderStroke(1.dp, Navy700),
                        colors = ButtonDefaults.outlinedButtonColors(contentColor = Slate200)
                    ) {
                        Icon(Icons.Default.ContentCopy, contentDescription = null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text("Copy", fontWeight = FontWeight.Bold)
                    }

                    Button(
                        onClick = {
                            val sendIntent: Intent = Intent().apply {
                                action = Intent.ACTION_SEND
                                putExtra(Intent.EXTRA_TEXT, reportText)
                                putExtra(Intent.EXTRA_SUBJECT, "${profile?.companyName ?: "Business"} Executive Report")
                                type = "text/plain"
                            }
                            val shareIntent = Intent.createChooser(sendIntent, "Share Executive Brief")
                            context.startActivity(shareIntent)
                        },
                        modifier = Modifier.weight(1f).testTag("share_report_button"),
                        shape = RoundedCornerShape(10.dp),
                        colors = ButtonDefaults.buttonColors(containerColor = Cyan500, contentColor = Navy950)
                    ) {
                        Icon(Icons.Default.Share, contentDescription = null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text("Share", fontWeight = FontWeight.Bold)
                    }
                }
            }
        }
    }
}
